package:
    name: themis-ml
    version: "0.0.2"

source:
    git_rev: v0.0.2
    git_url: https://github.com/cosmicBboy/themis-ml.git

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy
    - pathlib2
    - scikit-learn
    - pytest
  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - pathlib2
    - pytest

test:
  imports:
    - themis_ml
    - pandas
    - numpy
    - pathlib2
    - sklearn
    - pytest

about:
  home: https://github.com/cosmicBboy/themis-ml
  license: MIT
